[tool.poetry]
name = "sphinx-typer"
version = "0.1.0"
description = "Auto generate docs for typer commands."
authors = ["Brian Kohan <bckohan@gmail.com>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.9.0"
sphinx = "^7.0.0"
sphinx-click = "^5.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
