[tool.poetry]
name = "sphinxcontrib-typer"
version = "0.1.0"
description = "Auto generate docs for typer commands."
authors = ["Brian Kohan <bckohan@gmail.com>"]
license = "MIT"
readme = "README.rst"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Environment :: Web Environment",
    "Framework :: Sphinx :: Extension",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Documentation",
    "Topic :: Utilities",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

packages = [
  { include = "sphinxcontrib", from = "" }
]

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.9.0"
sphinx = "^7.0.0"
rich = "^13.7.0"

[tool.poetry.group.dev.dependencies]
sphinx-rtd-theme = "^2.0.0"
ipdb = "^0.13.13"
pytest = "^7.4.3"
isort = "^5.13.2"
pylint = "^3.0.3"
pytest-cov = "^4.1.0"
doc8 = "^1.1.1"
black = "^23.12.0"
mypy = "^1.7.1"
readme-renderer = {extras = ["md"], version = "^42.0"}
aiohttp = "^3.9.1"


[tool.poetry.group.html.dependencies]
selenium = "^4.16.0"
webdriver-manager = "^4.0.1"


[tool.poetry.group.pdf.dependencies]
cairosvg = "^2.7.1"
lxml = "^4.9.3"
tinycss2 = "^1.2.1"
cssselect2 = "^0.7.0"


[tool.poetry.group.png.dependencies]
pillow = "^10.1.0"
selenium = "^4.16.0"
webdriver-manager = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80
target-version = ['py38']
skip-string-normalization = true
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | \.venv
    | build
    | dist
    | doc
  )
)
'''

[tool.pytest.ini_options]
testpaths = [
    "tests/tests.py",
]
addopts = [
    "--doctest-modules",
    "--cov=sphinxcontrib.typer",
    "--cov-report=html",
    "--cov-fail-under=80",
    "--cov-report=term-missing:skip-covered",
    "--no-cov-on-fail",
    #"-x",
    #"--pdb",
    #"--flake8",
]

[tool.isort]
# isort configuration:
# https://github.com/timothycrosley/isort/wiki/isort-Settings
include_trailing_comma = true
use_parentheses = true
# See https://github.com/timothycrosley/isort#multi-line-output-modes
multi_line_output = 3
line_length = 79
